name=PluviometerSensor
version=1.0.0
author=Proagro Technology
maintainer=Jhonny Vásquez Jiménez
sentence=Lightweight library for tipping-bucket rain gauge.
paragraph=Provides tip counting and conversion to millimeters using configurable MME factor.
category=Sensors
url=https://github.com/jvasquez05/PluviometerSensor
architectures=*